from __future__ import annotations

from .editorial_prompt import EDITORIAL_IDENTITY, EDITORIAL_SCHEMA_IDENTITY

EDITORIAL_MODEL_ID = "Qwen/Qwen3-30B-A3B-Instruct-2507"
EDITORIAL_MODEL_REVISION = "110954009be4a882781a90356c7d2b8a9e3428dc"
EDITORIAL_QUANTIZATION = "bnb-4bit-nf4"
EDITORIAL_INFERENCE_ENGINE = "modal-transformers"
EDITORIAL_PROMPT_VERSION = EDITORIAL_IDENTITY
EDITORIAL_SCHEMA_VERSION = EDITORIAL_SCHEMA_IDENTITY
